### ISSUE TITLE
ERROR: ('Connection aborted.', error(104, 'Connection reset by peer'))

### ISSUE THREAD

**Issue by bhanukumar22** [StackStorm/st2-docker#115]
Hi All,

Im getting below error when I'm trying to run any command on st2.

root@784fdededd7:/# st2 action list
ERROR: ('Connection aborted.', error(104, 'Connection reset by peer'))

I see from the logs that, st2 is able to communicate to mongo, postgres and rabbitmq. No issues with that. Im cloning st2-docker on to my machine. The only change I do is, in docker-compose file I will be giving path to stackstorm dockerfile for building image. 
Please help, im stuck with the error from last 1 week and I'm not able to proceed with this.

Im adding the stackstorm dockerfile for reference.

[ae.txt](https://github.com/StackStorm/st2-docker/files/1824194/ae.txt)

**Comment by bigmstone** [comment]
This is likely due to a sync issue with our latest image. Can you perform a ‘docker pull‘ of the StackStorm image? That should resolve the issue. 

Details are in #112

**Comment by warrenvw** [comment]
Closing the issue since there's been no update in the last month. Please feel free to re-open if `docker pull` doesn't resolve the issue.

**Comment by Topher33** [comment]
I just did a fresh download of stackstorm:latest and still seeing ERROR: ('Connection aborted.', error(104, 'Connection reset by peer'))

**Comment by wilsonp** [comment]
me to

**Comment by vhristev** [comment]
I tried RABBITMQ_DEFAULT_USER=guest and RABBITMQ_DEFAULT_PASS=guest  and its not working for me I still receive

```
root@df160368fa19:/# st2 action list
ERROR: ('Connection aborted.', error(104, 'Connection reset by peer'))

```
```
~/Desktop/st2-docker(master*) » cat conf/rabbitmq.env                                                                                                                                                                                                          vhristev@vhristev-a01
RABBITMQ_DEFAULT_USER=guest
RABBITMQ_DEFAULT_PASS=guest
RABBITMQ_HOST=rabbitmq
RABBITMQ_PORT=5672
```

Even tried pulling latest image without success:
`docker pull stackstorm/stackstorm`
