### ISSUE TITLE
ST2_API_KEY

### ISSUE THREAD

**Issue by xxtaoqi** [StackStorm/st2-docker#233]
![image](https://user-images.githubusercontent.com/49810599/145033820-981ee4e2-e254-43bc-9274-07f55656aab5.png)

I want to know what is the ‘ST2_API_KEY’?
How do I get this value？

**Comment by armab** [comment]
See https://docs.stackstorm.com/authentication.html#api-keys documentation for the StackStorm API Keys.

**Comment by stevemuskiewicz** [comment]
I'll push up a PR with a clarification in the README for this as well since I didn't initially mention it when I updated the docs, thanks for bringing it to attention. 🙂

**Comment by xxtaoqi** [comment]
Thank you for your answers, but I still have a few questions.

**Problem Reproduction**
```
MacBook-Pro-8:st2-docker shansxu$ docker-compose exec st2api bash
st2@717cd2824c84:/opt/stackstorm$ st2 apikey create -k -m'{"name": "sstest"}' 
ERROR: 401 Client Error: Unauthorized
MESSAGE: Unauthorized - One of Token or API key required. for url: http://st2api:9101/apikeys
st2@717cd2824c84:/opt/stackstorm$ st2 apikey create -k -m '{"used_by": "st2admin"}'
ERROR: 401 Client Error: Unauthorized
MESSAGE: Unauthorized - One of Token or API key required. for url: http://st2api:9101/apikeys
```
Was it an error? How do I create an ApiKey in Docker？

**Comment by stevemuskiewicz** [comment]
@xxtaoqi first off, have you reviewed the Stackstorm docs to get an idea of how to use it?  Specifically the [quick start guide](https://docs.stackstorm.com/start.html) and also the [docker install](https://docs.stackstorm.com/install/docker.html) guide should be helpful here.

Also when you are running `st2` commands with a docker install, you will want to connect to the `st2client` container, not to the `st2api` container.  So try `docker-compose exec st2client bash` and see if that works better.

**Comment by xxtaoqi** [comment]
> 

@stevemuskiewicz 
The reason why I connected to the `ST2API` container is that it has failed in`ST2Client `container.

```
MacBook-Pro-8:st2-docker shansxu$ docker-compose exec st2client bash
bash: /opt/stackstorm/st2/bin/python: No such file or directory
Welcome to StackStorm HA v (Ubuntu 18.04.6 LTS GNU/Linux x86_64)
 * Documentation: https://docs.stackstorm.com/
 * Community: https://stackstorm.com/community-signup
 * Forum: https://forum.stackstorm.com/

 Here you can use StackStorm CLI. Examples:
   st2 action list --pack=core
   st2 run core.local cmd=date
   st2 run core.local_sudo cmd='apt-get update' --tail
   st2 execution list


root@0f00c3584a52:/opt/stackstorm# st2 apikey create -k -m '{"used_by": "st2admin"}'
bash: st2: command not found
root@0f00c3584a52:/opt/stackstorm# 
```

**Comment by stevemuskiewicz** [comment]
@xxtaoqi hmmm, this line in your output seems odd
```
bash: /opt/stackstorm/st2/bin/python: No such file or directory
```
Not sure but seems like something is messed up on your st2client container image... I don't know how that would normally happen but maybe worth trying to tear down the stack (`docker-compose down --remove-orphans -v`) and  do a `docker system prune -a` to clear out the existing images and then try the `docker-compose up -d` again?

Also double check your version of docker is recent enough as detailed in the [readme](https://github.com/StackStorm/st2-docker/blob/master/README.md).
